# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='commentm2m',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(related_name='likem2m', through='bbs.News2Like', to='bbs.Userinfo', verbose_name='点赞m2m关系'),
        ),
    ]
