# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20170918_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(max_length=255, verbose_name='url'),
        ),
    ]
