# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20170919_1745'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news2like',
            unique_together=set([('new', 'user')]),
        ),
    ]
