# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20170919_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='avatar',
            field=models.CharField(max_length=255, verbose_name='头像'),
        ),
    ]
