# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20170919_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.ManyToManyField(related_name='commentm2m', through='bbs.News2Comment', to='bbs.Userinfo', verbose_name='评论m2m关系表'),
        ),
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(related_name='likem2m', through='bbs.News2Like', to='bbs.Userinfo', verbose_name='点赞m2m关系'),
        ),
    ]
