# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20170919_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='news2comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.News2Comment'),
        ),
    ]
