# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20170905_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
