# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_userrole_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='host.UserRole'),
        ),
    ]
