# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_auto_20170907_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permissions',
            new_name='rolename',
        ),
    ]
